import { db } from "../db.js";

// Durable audit logging (spec sections 31-32). Callers pass only the
// whitelisted fields below — there is deliberately no "extra data" bag on
// this function, so a future caller cannot accidentally pass a password,
// token, or API key through to storage. Compare any new call site against
// this list before adding one.
export const AUDIT_ACTIONS = [
  "Login",
  "Login Failed",
  "Logout",
  "Password Reset Requested",
  "Password Reset Completed",
  "Account Provisioned",
  "Student Created",
  "Student Updated",
  "Enrollment Created",
  "Enrollment Updated",
  "Payment Submitted",
  "Payment Verified",
  "Payment Rejected",
  "Payment Voided",
  "Requirement Submitted",
  "Requirement Verified",
  "Requirement Rejected",
  "Role Changed",
  "Permission Changed",
  "Lead Converted",
  "Course Access Granted",
  "Course Access Revoked",
  "Master Brain Published",
  "Certificate Issued",
  "Integration Configuration Changed",
  "Admin Viewed As Student",
  "Training Created",
  "Training Updated",
  "Attendance Marked",
  "Attendance Updated",
  "Course Created",
  "Course Updated",
  "Course Published",
  "Lesson Completed",
  "Course Completed",
  "Certificate Eligible",
  "Certificate Reissued",
  "Feedback Submitted",
  "Video Feedback Uploaded",
  "Marketing Consent Granted",
  "Marketing Consent Updated",
  "Marketing Consent Revoked",
  "Testimonial Approved",
  "Incentive Granted",
  "Lead Created",
  "Registration Created",
  "Pipeline Stage Changed",
  "Follow-Up Created",
  "Follow-Up Completed",
  "Reservation Submitted",
  "Reservation Verified",
  "Duplicate Flagged",
  "Lead Assigned",
  "Consent Updated",
  // Phase 5 — GHL / Communications integration (spec sections 4, 11-13, 30, 57).
  "GHL Configuration Changed",
  "GHL Connection Tested",
  "GHL Mapping Changed",
  "GHL Outbox Manually Retried",
  "Message Template Changed",
  "Automation Rule Changed",
  "Message Sent",
  "Bulk Message Sent",
  // Phase 6 — Brand Master Brain + AI Business Tools (spec sections 6, 28, 65, 78).
  "AI Provider Configuration Changed",
  "AI Connection Tested",
  "AI Model Config Changed",
  "AI Tool Changed",
  "AI Usage Limit Changed",
  "Prompt Version Changed",
  "Master Brain Generated",
  "Master Brain Published",
  "Master Brain Revision Requested",
  "AI Tool Used",
  "AI Generation Completed",
  "AI Generation Failed",
  "AI Access Granted",
  "AI Access Revoked",
  // Phase 7 — Data Migration Framework (spec sections 6-8, 18).
  "Migration Batch Uploaded",
  "Migration Batch Validated",
  "Migration Dry Run Completed",
  "Migration Batch Approved",
  "Migration Batch Imported",
  "Migration Batch Rolled Back",
  // Phase 10 — M.A.I.A. Intelligence (spec sections 47, 81).
  "Intelligence Rule Created",
  "Intelligence Rule Changed",
  "Intelligence Rule Disabled",
  "Intelligence Signal Resolved",
  "Intelligence Signal Dismissed",
  "Intelligence Recommendation Generated",
  // Phase 11 — M.A.I.A. Creative Studio (spec sections 6, 52-55, 82).
  "Campaign Created",
  "Campaign Status Changed",
  "Creative Angle Generated",
  "Hook Generated",
  "Hook Status Changed",
  "Script Generated",
  "Script Status Changed",
  "Storyboard Generated",
  "Scene Prompt Generated",
  "Character Profile Created",
  "Creative Package Assembled",
  "Creative Package Status Changed",
  "Creative Test Created",
  "Creative Test Metrics Updated",
  // Phase 12 — M.A.I.A. Automation Studio (spec sections 39, 42, 84, 86).
  "Journey Created",
  "Journey Status Changed",
  "Automation Created",
  "Automation Version Created",
  "Automation Approved",
  "Automation Published",
  "Automation Activated",
  "Automation Paused",
  "Automation Archived",
  "Automation Run Started",
  "Automation Run Retried",
  "Automation Run Cancelled",
  "Automation Test Run",
  // Phase 13 — M.A.I.A. Website & Funnel Studio (spec sections 64-66, 116).
  "Website Project Created",
  "Website Page Created",
  "Website Page Status Changed",
  "Website Published",
  "Website Unpublished",
  "Website Rolled Back",
  "Funnel Created",
  "Funnel Status Changed",
  "Offer Created",
  "Form Created",
  "Form Destination Changed",
  "Form Submission Received",
  "Domain Configuration Changed",
  "Tracking Configuration Changed",
] as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[number];

interface AuditEntry {
  action: AuditAction;
  summary: string;
  actorUserId?: string | null;
  actorStudentId?: string | null;
  entityType?: string;
  entityId?: string;
}

export async function writeAuditLog(entry: AuditEntry) {
  await db.activityLog.create({
    data: {
      action: entry.action,
      summary: entry.summary,
      actorUserId: entry.actorUserId ?? null,
      actorStudentId: entry.actorStudentId ?? null,
      entityType: entry.entityType ?? null,
      entityId: entry.entityId ?? null,
    },
  });
}
